#!/bin/sh
#
# name2num: converts a single argument to the corresponding month number
#           sends result to stdout, exits 1 if error
#
	M="" ; RETVAL=0

	lcase()
	{
		echo $1 | tr "[A-Z]" "[a-z]"
	}

	case $(lcase $1) in
		jan*)	M=1	;;
		feb*)	M=2	;;
		mar*)	M=3	;;
		apr*)	M=4	;;
		may*)	M=5	;;
		jun*)	M=6	;;
		jul*)	M=7	;;
		aug*)	M=8	;;
		sep*)	M=9	;;
		oct*)	M=10	;;
		nov*)	M=11	;;
		dec*)	M=12	;;
		[1-9]|1[012])	M=$1	;;		# accept nums, too
		*)		RETVAL=1;;		# error condition
	esac
	echo $M
	exit $RETVAL
